version: "3"
services:
  bot-api:
      image: wayne/stepn-chart:0.0.1
      hostname: stepn-chart
      ports:
        - 8083:80

      stdin_open: true

      tty: true

      restart: unless-stopped

      volumes:
        - /home/wayne/dv/stepn-market-info/db:/usr/local/apache2/htdocs/db:ro
      container_name: stepn-chart
      networks:
        - web_wayne-net

networks:
  web_wayne-net:
    external: true